#!/bin/bash

sudo wget http://goo.gl/vewCLL -O /etc/apt/sources.list.d/rpimonitor.list
sudo apt-key adv --recv-keys --keyserver keyserver.ubuntu.com 2C0D3C0F

sudo apt-get update
sudo apt-get install rpimonitor -y
    
sudo apt-get update
sudo apt-get upgrade -y
sudo /etc/init.d/rpimonitor update




curl -sL https://deb.nodesource.com/setup_7.x | sudo -E bash -
sudo apt-get install -y nodejs build-essential mc nano git wget






